channels:
  - conda-forge
  - bioconda
  - defaults
  - default
dependencies:
  - python=3.10.2
  - numpy=1.21.4
  - pandas=1.3.4
  - h5py=3.6.0
  - pyreadr=0.4.4
  - matplotlib=3.4.3
  - brewer2mpl=1.4.1
  - pip
  - umap-learn=0.5.3
  - scipy=1.7.2
  - pip:
    - scikit-learn==1.0.2

